### ROOT
GET http://localhost:8080/


### publish
POST http://localhost:8080/measurements
content-type: application/json

{"deviceID":"998877","measurements":[{"sensorID":"sensor1","sensorTypeID":"float","value":"12.34"},{"sensorID":"sensor1","sensorTypeID":"float","value":"56.78"}]}
