name: okaki_device_bridge
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/okaki-gardening/okaki-device-bridge

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.3.0
  collection: ^1.17.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  dart_appwrite: ^8.0.0
  dotenv: ^4.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0

